name: Deploy Monorepo to EC2

on:
  push:
    branches: ["master"]


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install Backend Dependencies
          working-directory: ./backend
          run: npm install

        - name: Generate Prisma Client
          working-directory: ./backend
          run: npx prisma generate

        # - name: Build Backend (Optional)
        #   working-directory: ./backend
        #   run: npm run build

        # - name: Install Frontend Dependencies
        #   working-directory: ./frontend
        #   run: npm install

        # - name: Build Frontend
        #   working-directory: ./frontend
        #   run: ng build --configuration production

        - name: Copy Files to EC2
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: "./*"
            target: "/home/ec2-user/backend/"  


        - name: Restart Backend on EC2
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                cd /home/ec2-user/backend
                npm install
                npx prisma generate
                pm2 restart index.js
